### ISSUE TITLE
it not work

### ISSUE THREAD

**Issue by lvtoo** [abe33/atom-figlet#14]
[Enter steps to reproduce:]

1. just run
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**:  Windows 10
**Thrown From**: [figlet](https://github.com/abe33/atom-figlet) package 0.5.4

### Stack Trace

Uncaught TypeError: editor.getCommentStrings is not a function

```
At C:\Users\Administrator\.atom\packages\figlet\lib\figlet.coffee:68

TypeError: editor.getCommentStrings is not a function
    at Object.getTextToConvert (/packages/figlet/lib/figlet.coffee:68:117)
    at Object.convert (/packages/figlet/lib/figlet.coffee:38:44)
    at FigletFontView.module.exports.FigletFontView.confirmed (/packages/figlet/lib/figlet-font-view.coffee:62:20)
    at FigletFontView.module.exports.SelectListView.confirmSelection (/packages/figlet/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /packages/figlet/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/packages/figlet/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/packages/figlet/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -7:17.5.0 core:paste (input.hidden-input)
 26x -6:53.3.0 core:backspace (input.hidden-input)
  2x -6:03.4.0 figlet:convert (input.hidden-input)
  4x -3:20.1.0 figletify:convert (input.hidden-input)
     -3:07.9.0 core:undo (input.hidden-input)
     -2:43.3.0 core:backspace (input.hidden-input)
  9x -1:27.4.0 figlet:convert (input.hidden-input)
 12x -0:59.1.0 core:backspace (input.hidden-input)
     -0:30.8.0 figlet:convert (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
docblockr 0.13.7 
figlet 0.5.4 
figletify 0.2.2 
minimap 4.29.9 
nv-dark-ui 3.0.8 
```

**Comment by stanmarc** [comment]
Use the link below to manually edit the source code: 
https://github.com/abe33/atom-figlet/issues/9#issuecomment-465178311
