### ISSUE TITLE
Uncaught TypeError: editor.getCommentStrings is not a function

### ISSUE THREAD

**Issue by astrolemonade** [abe33/atom-figlet#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [figlet](https://github.com/abe33/atom-figlet) package 0.5.4

### Stack Trace

Uncaught TypeError: editor.getCommentStrings is not a function

```
At C:\Users\catal\.atom\packages\figlet\lib\figlet.coffee:68

TypeError: editor.getCommentStrings is not a function
    at Object.getTextToConvert (/packages/figlet/lib/figlet.coffee:68:117)
    at Object.convert (/packages/figlet/lib/figlet.coffee:38:44)
    at FigletFontView.module.exports.FigletFontView.confirmed (/packages/figlet/lib/figlet-font-view.coffee:62:20)
    at FigletFontView.module.exports.SelectListView.confirmSelection (/packages/zentabs/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /packages/zentabs/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/packages/zentabs/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/packages/zentabs/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:46.4.0 editor:consolidate-selections (input.hidden-input)
     -0:46.4.0 core:cancel (input.hidden-input)
  3x -0:38.8.0 editor:newline (input.hidden-input)
     -0:37.4.0 core:backspace (input.hidden-input)
     -0:36.2.0 intentions:highlight (input.hidden-input)
     -0:36 core:save (input.hidden-input)
  2x -0:33.8.0 intentions:highlight (input.hidden-input)
     -0:33.2.0 figlet:convert (input.hidden-input)
     -0:31.2.0 editor:consolidate-selections (input.hidden-input)
     -0:31.2.0 core:cancel (input.hidden-input)
  2x -0:17.8.0 intentions:highlight (input.hidden-input)
     -0:16.9.0 figlet:convert (input.hidden-input)
 63x -0:13.6.0 core:move-down (input.hidden-input)
     -0:09.4.0 core:confirm (input.hidden-input)
 34x -0:08.5.0 core:move-down (input.hidden-input)
     -0:06.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-bracket-highlight 0.3.2 
autocomplete-racer 0.1.3 
block-comment 0.4.3 
busy-signal 2.0.0 
clang-format 2.0.7 
color-tabs 0.1.8 
figlet 0.5.4 
file-icons 2.1.29 
fonts 3.2.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-rust 0.4.12 
minimap 4.29.9 
open-terminal-here 2.3.2 
rustfmt 0.1.3 
tree-view-autoresize 2.3.0 
zentabs 0.8.9 
```

**Comment by stanmarc** [comment]
Use the link below to manually edit the source code: 
https://github.com/abe33/atom-figlet/issues/9#issuecomment-465178311
